#: include Clock/clock.kv

<Menu>:

    MDBottomNavigation:

        MDBottomNavigationItem:
            name: "Clock"

            Clock:

        MDBottomNavigationItem:
            name: "Alarm"
            

        MDBottomNavigationItem:
            name: "Timer"
            

        MDBottomNavigationItem:
            name: "Timepiece"
            

        MDBottomNavigationItem:
            name: "Info"
            